readonly DOTFILES_DIR=~/.dotfiles

readonly DEV_WORKSPACE=~/Development

readonly DEV_WORKSPACE_TOOLS=$DEV_WORKSPACE/tools
readonly DEV_WORKSPACE_GIT_ENTREPRENEURSHIP=$DEV_WORKSPACE/git-entrepreneurship
readonly DEV_WORKSPACE_GIT_PERSONAL=$DEV_WORKSPACE/git-personal
readonly DEV_WORKSPACE_GIT_WORK=$DEV_WORKSPACE/git-work
readonly DEV_WORKSPACE_KEYS=$DEV_WORKSPACE/keys
readonly DEV_WORKSPACE_TMP=$DEV_WORKSPACE/tmp

mkdir -p $DEV_WORKSPACE_TOOLS \
  $DEV_WORKSPACE_GIT_ENTREPRENEURSHIP \
  $DEV_WORKSPACE_GIT_PERSONAL \
  $DEV_WORKSPACE_GIT_WORK \
  $DEV_WORKSPACE_KEYS \
  $DEV_WORKSPACE_TMP
