DEV_WORKSPACE=~/Development

DEV_WORKSPACE_TOOLS=$DEV_WORKSPACE/tools
DEV_WORKSPACE_LABS=$DEV_WORKSPACE/labs
DEV_WORKSPACE_GIT_PERSONAL=$DEV_WORKSPACE/git-personal
DEV_WORKSPACE_GIT_WORK=$DEV_WORKSPACE/git-work
DEV_WORKSPACE_TMP=$DEV_WORKSPACE/tmp

function create_development_workspace() {
  echo "<<<<<< Creating development workspace"

  mkdir -p $DEV_WORKSPACE_SERVERS $DEV_WORKSPACE_TOOLS \
  $DEV_WORKSPACE_LABS $DEV_WORKSPACE_GIT_PERSONAL \
  $DEV_WORKSPACE_GIT_WORK $DEV_WORKSPACE_TMP

  echo "$DEV_WORKSPACE_TOOLS"
}
